### ISSUE TITLE
Refactor X-Hub-Signature validation

### ISSUE THREAD

**Issue by nwf** [octokit/webhooks.net#24]
### Describe the feature

https://github.com/octokit/webhooks.net/blob/95e10f99238339f5ae712e73b5f4279debef7646/src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs#L66 requires a `HttpContext` object only for its `header` and for generating a response in the case of failure.  Unfortunately. `HttpContext`s are sometimes hard to come by; for example, Azure Functions, at least as of runner version 4, for example, provide only `HttpRequest`s and not the full `HttpContext`.

Therefore, it would be quite nice and DRY if this method could be split into a worker and wrapper, with the worker taking the already-extracted signature header and returning a `HttpStatusCode` and `String` for the body, and the wrapper adapting for the ASP.Net `HttpContext` object.

**Comment by JamieMagee** [comment]
Okay, so to clarify you'd like an interface that looks something like this:

```c#
public static class GitHubWebhookExtensionsWorker
{
    public static VerifyResult VerifyContentType(HttpRequest request, string expectedContentType);

    private static async Task<string> GetBodyAsync(HttpRequest request);

    private static async Task<VerifyResult> VerifySignatureAsync(HttpContext context, string secret, string body)
}
```

where `VerifyResult` is something like:

```c#
public sealed record VerifyResult
{
    public bool IsSuccess { get; init; } = null!;

    public int? ResponseCode { get; init; }

    public string? ResponseMessage { get; init; }
}
```

and `MapGitHubWebhooks` will call `GitHubWebhookExtensionsWorker` methods checking `IsSuccess`?

**Comment by nwf** [comment]
That seems plausible, though maybe `GitHubWebhookUtilities` rather than `...ExtensionsWorker`?

Is it possible to make `VerifyResult` parametric on its success case?  Then `VerifySignatureAsync` can return `VerifyResult<bool>` and `MapGitHubWebhooks` could also be split into the preflight checks (fairly reusable) and flight (ASP.Net specific) bits?  That is, pull https://github.com/octokit/webhooks.net/blob/95e10f99238339f5ae712e73b5f4279debef7646/src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs#L20-L33 out to their own method (adjusted to take a `HttpRequest` and to return a `Task<VerifyResult<string>>` capturing the body of a verified message) in the worker class?
