### ISSUE TITLE
workflow_job hook does not deserialize the workflow_job object

### ISSUE THREAD

**Issue by nwf** [octokit/webhooks.net#25]
### Describe the bug

https://github.com/octokit/webhooks.net/blob/95e10f99238339f5ae712e73b5f4279debef7646/src/Octokit.Webhooks/Events/WorkflowJobEvent.cs defines `WorkflowJobEvent` simply as a generic `WebhookEvent` without adding the `workflow_job` object documented in https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job .  This significantly decreases, likely to near zero, the utility of the hook.

### Steps to reproduce

Attempt to override `ProcessWorkflowJobWebhookAsync` and condition on the `workflow_job` `label` attribute.  It is not possible to access, as the callback is not passed the raw JSON message nor is the `workflow_job` sub-object exposed via the `WorkflowJobEvent` argument.

### Expected behaviour

The `workflow_job` object should be available to the callback.

**Comment by JamieMagee** [comment]
Good catch! I think at the time of writing the first iteration of this library, that event was undocumented in the GitHub documentation. Clearly that's changed, and the `WorkflowJobEvent` class should be properly completed.
