### ISSUE TITLE
[FEAT]: Include `deployment` node in WorkflowJob events

### ISSUE THREAD

**Issue by lineville** [octokit/webhooks.net#259]
### Describe the need

When a `WorkflowJob` is associated with an environment, it will include a `deployment` property in the json payload, which is currently left off. I'd like to contribute a PR that adds support for including this additional property in these webhook messages.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamieMagee** [comment]
Thanks for the issue. I've assigned it to you.

We don't have great documentation for new contributors, but there should be enough examples in the codebase to draw from.
