### ISSUE TITLE
Change all applicable IDs from int to long

### ISSUE THREAD

**Issue by JamieMagee** [octokit/webhooks.net#30]
See:
- https://github.com/octokit/octokit.net/issues/2351
- https://github.com/octokit/octokit.net/pull/2352

**Comment by JamieMagee** [comment]
@moodymatt you're right. I haven't had much time recently to dedicate to maintenance here, but I opened a quick PR at #38.

**Comment by moodymatt** [comment]
> @moodymatt you're right. I haven't had much time recently to dedicate to maintenance here, but I opened a quick PR at #38.

@JamieMagee awesome work  and thanks for the quick response!  I'll keep an eye out for the PR completing and update my references to the latest version of the SDK once all the checks have passed and its been merged down.
