### ISSUE TITLE
Complete `merge_queue_entry` and `repository_ruleset` events

### ISSUE THREAD

**Issue by JamieMagee** [octokit/webhooks.net#340]
The initial scaffolding for [`merge_queue_entry`][1] and [`repository_ruleset`][2] was completed in #329. However, the complete definitions still need to be completed.

[1]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_queue_entry 
[2]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_ruleset

**Comment by JamieMagee** [comment]
Yeah, absolutely!

**Comment by Laxynium** [comment]
Is merge_queue_entry still supported? I cannot find it in github documentation https://docs.github.com/en/webhooks/webhook-events-and-payloads#merge_queue_entry

**Comment by JamieMagee** [comment]
Yes? I'll follow-up on that. Thanks for the work on `repository_ruleset`!
