### ISSUE TITLE
[BUG]: Inconsistent types on WebHook models

### ISSUE THREAD

**Issue by ilmax** [octokit/webhooks.net#524]
### What happened?

Different types exposes similar properties using different underlying types, I was looking at the `*_at` properties in the class
[WorkflowJob](https://github.com/octokit/webhooks.net/blob/b3bb0e872ad8e09f9b11c2f2e29ad0022244494e/src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJob.cs#L62-L75) and seems like those properties are exposed as string while most of the time they're exposes as `DateTimeOffset`.

Having a quick look [here](https://github.com/search?q=repo%3Aoctokit%2Fwebhooks.net+_at%22%29&type=code&p=3) I found some more occurrences [here](https://github.com/octokit/webhooks.net/blob/b3bb0e872ad8e09f9b11c2f2e29ad0022244494e/src/Octokit.Webhooks/Models/RepositoryRulesetEvent/RepositoryRuleset.cs#L43-L47) and [here](https://github.com/octokit/webhooks.net/blob/b3bb0e872ad8e09f9b11c2f2e29ad0022244494e/src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJobStep.cs#L20-L21)

Can we unify those and use `DateTimeOffset` everywhere? This will be a breaking change so it requires a major version bump.

### Versions

2.2.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamieMagee** [comment]
@ilmax thanks for opening the bug. I think #525 resolves this, but I agree that this is a breaking change. I'll see if we have any more immediate breaking changes that we want to batch together into a 3.0.0 release.

**Comment by ilmax** [comment]
Looking forward to version 3 soon then, thank you for the quick fix!
