### ISSUE TITLE
[BUG]: InvalidCastException during String to StringEnum Conversion in WorkflowJobStatus Deserialization

### ISSUE THREAD

**Issue by Monica-Zhang-git** [octokit/webhooks.net#551]
### What happened?
After upgrading Octokit.Webhooks.AspNetCore from 1.5.1 to 2.2.2 we noticed the test failed. we encountered an InvalidCastException while attempting to deserialize webhook payloads into the WorkflowJobStatus enum using the SimpleJsonSerializer in the Octokit.Webhooks library. 

The error message is as following:
> 
`   System.InvalidCastException : Invalid cast from 'System.String' to 'Octokit.Webhooks.Extensions.StringEnum`1[[Octokit.Webhooks.Models.WorkflowJobEvent.WorkflowJobStatus, Octokit.Webhooks, Version=2.0.0.0, Culture=neutral, PublicKeyToken=xxx]]'.`

Could you please provide guidance or a potential fix for this issue? Any help from the Octokit team would be greatly appreciated.

### Versions

Octokit.Webhooks.AspNetCore v2.2.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamieMagee** [comment]
@Monica-Zhang-git are you able to provide a sample payload or some sample code to help reproduce the issue?

**Comment by Monica-Zhang-git** [comment]
@JamieMagee, Thanks for following up on this issue. We have solved it. Cheers
