### ISSUE TITLE
[BUG]: ProcessWorkflowRunWebhookAsync not called for `in_progress` messages

### ISSUE THREAD

**Issue by justinmchase** [octokit/webhooks.net#580]
### What happened?

The webhook event is not firing for `in_progress` webhook messages.

- [The handler](https://github.com/octokit/webhooks.net/blob/main/src/Octokit.Webhooks/WebhookEventProcessor.cs#L1290) is missing a case for the `in_progress` event.

---

![Screenshot 2024-09-28 at 9 44 34 AM](https://github.com/user-attachments/assets/b3f00f65-1cd1-4cdc-a6df-6f17cc701753)

But this code appears to filter out all events except for `requested` and `completed`...

![Screenshot 2024-09-28 at 9 43 07 AM](https://github.com/user-attachments/assets/a47a895a-de8f-45af-810a-32b05ae5640c)

### Versions

dotnet `13.0.1`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by allantargino** [comment]
I experimented the same bug in my current project. I was also able to reproduce it in the [AspNetCore Sample](https://github.com/octokit/webhooks.net/tree/main/samples/AspNetCore).

I just send the potential fix (which made the sample work).

**Comment by justinmchase** [comment]
Thank you, looks perfect.
