### ISSUE TITLE
Add `IsBot` field to User model

### ISSUE THREAD

**Issue by lipa44** [octokit/webhooks.net#95]
### Describe the feature

Nowadays, webhooks (including github ones) often uses by developers to automate different processes.

As soon it is used to automate something, it leads to creating GitHub Apps (**bots**) to manage those processes.

My idea is to add `IsBot` field to User model to make it easier to manage permissions or business logic stuff inside applications using webhooks, where bots are using (instead of duplicate `User.Type == == UserType.Bot` every time or creating own extensions for User model).

_P.S. inspired while working on our university project, where we're trying to automate code review in PR's in context of programming discipline._

_Problem, for example, appeared after configuring `IssueCommentHandler`. In our logic GitHub App should manage pull_request_comments (issue comments) and write it's own on each comment. But it rounds after sending message where `sender` is bot - it is starting to handle it's own comments. The solution of this problem is check if `sender` is **bot** before creating new comment, but it's quite strange that your domain model (user) doesn't have `IsBot` field._

**Comment by JamieMagee** [comment]
The models in `Octokit.Webhooks` track the GitHub webhook events and payloads[^1]. Unfortunately `is_bot` isn't part of any events or payloads.

I'd recommend creating your own extension class to handle this. Something as simple as this would likely work:

```csharp
public static class UserExtensions
{
  public static bool IsBot(this User user) => user.Type == UserType.Bot;	
}
```

I don't think that this extension on its own is enough to create extensions in the `Octokit.Webhooks` package.

[^1]: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
